name: Path filter test
on:
  pull_request:
    branches:
      - 'master'
    paths:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: cat functions/server/index.ts
